# Generated by Django 4.2.11 on 2026-06-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('POR_ESTUDIANTE', 'Por Estudiante'), ('POR_MATERIA', 'Por Materia'), ('POR_CICLO', 'Por Ciclo'), ('GENERAL', 'General')], max_length=15)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(default=dict)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('DASHBOARD', 'Dashboard')], default='PDF', max_length=10)),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'reporte',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
