# Generated by Django 4.2.11 on 2026-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_managers_remove_usuario_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
