# Generated by Django 4.2.11 on 2026-06-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDE', 'Tarde'), ('JUSTIFICADO', 'Justificado')], max_length=12)),
                ('confianza', models.FloatField(default=0.0)),
                ('estudiante_id', models.IntegerField()),
                ('horario_id', models.IntegerField()),
            ],
            options={
                'db_table': 'asistencia',
                'ordering': ['-fecha', '-hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(max_length=100, unique=True)),
                ('collection_id', models.CharField(default='sacarf_faces', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('estudiante_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'registro_facial',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.BooleanField(default=False)),
                ('confianza', models.FloatField(default=0.0)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('estudiante_id', models.IntegerField()),
                ('registro_facial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='asistencia.registrofacial')),
            ],
            options={
                'db_table': 'reconocimiento',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('documento_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('estudiante_id', models.IntegerField()),
                ('docente_aprueba_id', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('comentario_docente', models.TextField(blank=True)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='asistencia.asistencia')),
            ],
            options={
                'db_table': 'justificacion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='reconocimiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia', to='asistencia.reconocimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante_id', 'horario_id', 'fecha')},
        ),
    ]
