# Generated by Django 4.2.11 on 2026-07-16 04:58

import apps.asistencia.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificacion',
            name='documento_url',
        ),
        migrations.AddField(
            model_name='justificacion',
            name='documento',
            field=models.FileField(default='', help_text='Comprobante médico en formato PNG o JPG', upload_to=apps.asistencia.models.ruta_comprobante_medico, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
