# Generated by Django 4.2.11 on 2026-06-24 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofacial',
            name='estudiante',
            field=models.OneToOneField(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='registro_facial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='registro_facial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='asistencia.registrofacial'),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='asistencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='asistencia.asistencia'),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='docente_aprueba',
            field=models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.horario'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='reconocimiento',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia', to='asistencia.reconocimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'horario', 'fecha')},
        ),
    ]
