# Generated by Django 4.2.11 on 2026-06-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en semestres')),
                ('modalidad', models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial'), ('HIBRIDA', 'Híbrida')], max_length=10)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(help_text='Número del ciclo (1, 2, 3, ...)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='academico.carrera')),
            ],
            options={
                'db_table': 'ciclo',
                'unique_together': {('num', 'carrera')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('creditos', models.PositiveIntegerField()),
                ('horas_semanales', models.PositiveIntegerField()),
                ('docente_id', models.IntegerField(blank=True, null=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.carrera')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.ciclo')),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('minutos_tolerancia', models.PositiveIntegerField(default=10, help_text='Minutos de tolerancia para tardanza')),
                ('aula', models.CharField(blank=True, max_length=50)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.materia')),
            ],
            options={
                'db_table': 'horario',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id', models.IntegerField()),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.carrera')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.ciclo')),
            ],
            options={
                'db_table': 'matricula',
                'ordering': ['-fecha_matricula'],
                'unique_together': {('estudiante_id', 'ciclo')},
            },
        ),
    ]
