# Generated by Django 6.0.6 on 2026-06-24 03:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Carrera')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('duracion', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('modalidad', models.CharField(choices=[('VIRTUAL', ' Virtual'), ('PRESENCIAL', 'Presencial'), ('HIBRIDA', 'Hibrida')], default='PRESENCIAL')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paralelgo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')])),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Materia')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('horasSemanales', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ciclo', models.IntegerField(default=1, help_text='Cuantos ciclo tiene la carrera', verbose_name='Numero del ciclo')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio del ciclo')),
                ('fecha_fin', models.DateField(verbose_name='Fin del ciclo')),
                ('estado', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='academico.carrera')),
            ],
        ),
    ]
