# Generated by Django 6.0.6 on 2026-06-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='paralelgo',
            new_name='paralelo',
        ),
    ]
