# Generated by Django 4.2.11 on 2026-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('usuario_nombre', models.CharField(default='desconocido', max_length=150)),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('servicio', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('registro_id', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('datos_modificados', models.JSONField(blank=True, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitoring_registroauditoria',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='monitoring__fecha_h_6fc95c_idx'), models.Index(fields=['servicio'], name='monitoring__servici_b52cf3_idx'), models.Index(fields=['modelo'], name='monitoring__modelo_c448e5_idx'), models.Index(fields=['usuario_id'], name='monitoring__usuario_f9074f_idx'), models.Index(fields=['accion'], name='monitoring__accion_a17f31_idx')],
            },
        ),
    ]
